# yaml-language-server: $schema=https://raw.githubusercontent.com/goreleaser/goreleaser/v2.3.2/www/docs/static/schema.json

# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: tfc

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

release:
  prerelease: auto
  name_template: "v{{.Version}}"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^ci'
      - '^build'
      - '^chore'
      - '^refactor'
      - Merge pull request
      - Merge branch

builds:
  - main: ./cmd/tfc
    binary: bin/tfc
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    ldflags:
      - -s -w -X github.com/zkhvan/tfc/internal/build.Version={{.Version}} -X github.com/zkhvan/tfc/internal/build.Date={{time "2006-01-02"}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

brews:
  - directory: Formula
    repository:
      owner: zkhvan
      name: homebrew-tap
      branch: brew-releases/{{ .Version }}
      token: "{{ .Env.GITHUB_PAT_TOKEN }}"
      pull_request:
        enabled: true
        base:
          owner: zkhvan
          name: homebrew-tap
          branch: main
    url_template: https://github.com/zkhvan/tfc/releases/download/{{ .Tag }}/{{ .ArtifactName }}
    download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy

    custom_require: ../lib/private_strategy

    # Git author used to commit to the repository.
    commit_author:
      name: goreleaserbot
      email: goreleaserbot@example.com
    commit_msg_template: Brew formula update for {{ .ProjectName }} version {{ .Tag }}

    install: |
      bin.install "tfc"

checksum:
  name_template: "checksums.txt"
