name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write  # Required for creating releases and uploading assets

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0        # Ensures full history for GoReleaser

      - id: setup-go
        name: Set Up Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: go.mod

      - id: run-goreleaser
        name: Run goreleaser
        uses: goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf # v6.1.0
        with:
          version: v2.3.2
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PAT_TOKEN: ${{ secrets.TFC_GITHUB_TOKEN }}
